include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

linter:
  rules:
    - always_declare_return_types
    - constant_identifier_names: true
    - always_specify_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_print
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - camel_case_extensions
    - camel_case_types
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_function_declarations_over_variables
    - prefer_spread_collections
    - sort_child_properties_last
    - use_function_type_syntax_for_parameters
    - use_named_constants
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_truncating_division
    - valid_regexps

flutter:
  use_material_design: true

dart:
  prefer_const_constructors_in_immutables: true
  prefer_final_fields: true





























