name: simple_todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #for local database [isar]
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.1
  #for date manage
  intl:
  #for state management
  get: ^4.7.2
  #for icon SVG
  flutter_svg: ^2.0.17
  #for debugging
  logger:
  #for file uploading
  image_picker:
  file_picker:
  #for icon :
  flutter_launcher_icons: ^0.14.4
  get_storage: ^2.1.1
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
#  analyzer: ^4.7.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/animation/




  fonts:
    - family: satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
        - asset: assets/fonts/satoshi/Satoshi-BlackItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
        - asset: assets/fonts/satoshi/Satoshi-BoldItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Italic.otf
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
        - asset: assets/fonts/satoshi/Satoshi-LightItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
        - asset: assets/fonts/satoshi/Satoshi-MediumItalic.otf
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf

